/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MOMoTUiModule extends at.ac.tuwien.big.momot.lang.ui.AbstractMOMoTUiModule {
	public MOMoTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
