/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang;

import org.eclipse.xtext.generator.IGenerator;

import com.google.inject.Binder;

import at.ac.tuwien.big.momot.lang.scoping.MOMoTScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MOMoTRuntimeModule extends at.ac.tuwien.big.momot.lang.AbstractMOMoTRuntimeModule {
	@Override
	public void configureIScopeProviderDelegate(Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
			.annotatedWith(com.google.inject.name.Names.named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
			.to(MOMoTScopeProvider.class);
	}
	
	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return super.bindIGenerator();
	}
}
