/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang;

import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.compiler.XbaseCompiler;

import com.google.inject.Binder;

import at.ac.tuwien.big.momot.lang.jvmmodel.MOMoTCompiler;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MOMoTRuntimeModule extends at.ac.tuwien.big.momot.lang.AbstractMOMoTRuntimeModule {
	@Override
	public void configureIScopeProviderDelegate(Binder binder) {
		super.configureIScopeProviderDelegate(binder);
	}
	
	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return MOMoTCompiler.class;
	}
	
	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return super.bindIGenerator();
	}
}
