/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang;

/**
 * Initialization support for running Xtext languages
 * without equinox extension registry
 */
public class MOMoTStandaloneSetup extends MOMoTStandaloneSetupGenerated {

   public static void doSetup() {
      new MOMoTStandaloneSetup().createInjectorAndDoEMFRegistration();
   }
}
