<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="nextReleaseProblem" nsURI="http://model.nrp" nsPrefix="NRP">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NRP">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" lowerBound="1"
        upperBound="-1" eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableArtifacts" lowerBound="1"
        upperBound="-1" eType="#//SoftwareArtifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" lowerBound="1"
        upperBound="-1" eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assigns" lowerBound="1"
        upperBound="-1" eType="#//Valuation" eOpposite="#//Valuation/assignedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CostType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareArtifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//SoftwareArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="costs" lowerBound="1" upperBound="-1"
        eType="#//Cost" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributesTo" lowerBound="1"
        upperBound="-1" eType="#//RequirementRealisation" eOpposite="#//RequirementRealisation/dependsOn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" eOpposite="#//Solution/selectedArtifacts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuations" lowerBound="1"
        upperBound="-1" eType="#//Valuation" containment="true" eOpposite="#//Valuation/requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realisations" upperBound="-1"
        eType="#//RequirementRealisation" containment="true" eOpposite="#//RequirementRealisation/requirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combines" upperBound="-1"
        eType="#//Valuation" eOpposite="#//Valuation/contributesTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementRealisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirement" eOpposite="#//Requirement/realisations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" lowerBound="1"
        upperBound="-1" eType="#//SoftwareArtifact" eOpposite="#//SoftwareArtifact/contributesTo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedArtifacts" upperBound="-1"
        eType="#//SoftwareArtifact" eOpposite="#//SoftwareArtifact/solutions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CostType">
    <eLiterals name="MONEY"/>
    <eLiterals name="TIME" value="1"/>
    <eLiterals name="MANPOWER" value="2"/>
    <eLiterals name="RESOURCES" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valuation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirement" eOpposite="#//Requirement/valuations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedBy" lowerBound="1"
        upperBound="-1" eType="#//Customer" eOpposite="#//Customer/assigns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributesTo" upperBound="-1"
        eType="#//Requirement" eOpposite="#//Requirement/combines"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
