/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.momot.lang.services.MOMoTGrammarAccess;

public class MOMoTParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MOMoTGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.momot.lang.parser.antlr.internal.InternalMOMoTParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.momot.lang.parser.antlr.internal.InternalMOMoTParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MOMoTSearch";
	}
	
	public MOMoTGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MOMoTGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
