/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang.ui;

import at.ac.tuwien.big.momot.lang.ui.hover.MOMoTDispatchingTextHover;
import at.ac.tuwien.big.momot.lang.ui.hover.MOMoTHoverProvider;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hover.IEObjectHover;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MOMoTUiModule extends at.ac.tuwien.big.momot.lang.ui.AbstractMOMoTUiModule {
   public MOMoTUiModule(final AbstractUIPlugin plugin) {
      super(plugin);
   }

   @Override
   public Class<? extends IEObjectHover> bindIEObjectHover() {
      return MOMoTDispatchingTextHover.class;
   }

   @Override
   public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
      return MOMoTHoverProvider.class;
   }
}
