/*
 * generated by Xtext
 */
package at.ac.tuwien.big.momot.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.momot.lang.ui.internal.MOMoTActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MOMoTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MOMoTActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MOMoTActivator.getInstance().getInjector(MOMoTActivator.AT_AC_TUWIEN_BIG_MOMOT_LANG_MOMOT);
	}
	
}
